### ISSUE TITLE
Links não operacionais no index (base)

### ISSUE THREAD

**Issue by RodrigoDias04** [Lourencol18/Lourencol18.github.io#2]
https://github.com/Lourencol18/Lourencol18.github.io/blob/6b1ec97634eb86f4294e9a3f83e21b1289011e03/index.html#L29

Na tua pagina principal não aparecem os links para os Laboratórios.

**Comment by Lourencol18** [comment]
Como assim
Não aparecerem estão lá em baixo ?

**Comment by Lourencol18** [comment]
![Uploading image.png…]()

**Comment by Lourencol18** [comment]
![Uploading IMG_9414.jpeg…]()

**Comment by RodrigoDias04** [comment]
Desculpa não dei scroll
