### ISSUE TITLE
Link para os labs

### ISSUE THREAD

**Issue by auriacagigal** [Lourencol18/Lourencol18.github.io#6]
https://github.com/Lourencol18/Lourencol18.github.io/blob/7fc2d33b305b4c2ee2e79cf4a44d5ba99c7f7936/index.html#L7

Os links para os labs não estão presentes no código

**Comment by Lourencol18** [comment]
Estao sim da scroll na página …

**Comment by auriacagigal** [comment]
Vi agora, desculpa Lourenço
Lourenço ***@***.***> escreveu em sex., 11/10/2024 às 14:11 :
